a=input("input value for a: ")
a=int(a)
b=input("input value for b: ")
b=int(b)
addition=a+b
subtraction=a-b
multiplication=a*b
division=a/b
print("addition =",addition)
print("subtraction =",subtraction)
print("multiplication =",multiplication)
print("division =",division)